version: '3.8'

services:
  # === BASE DE DONNÃ‰ES ===
  db-clients:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clients_db
    ports:
      - "5433:5432"
    volumes:
      - db_clients_data:/var/lib/postgresql/data

  db-produits:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: produits_db
    ports:
      - "5434:5432"
    volumes:
      - db_produits_data:/var/lib/postgresql/data

  db-commandes:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: commandes_db
    ports:
      - "5435:5432"
    volumes:
      - db_commandes_data:/var/lib/postgresql/data

  # === MESSAGE BROKER ===
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  db_clients_data:
  db_produits_data:
  db_commandes_data: